name: Cleanup
on:
  push:
    #branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Run retention action
        uses: snok/container-retention-policy@v3.0.0
        with:
          image-names: psp-webdyne-fortune
          cut-off: 1h
          keep-n-most-recent: 4
          account: user
          token: ${{ secrets.GHCR_PAT }}   # or GITHUB_TOKEN if appropriate
